### ISSUE TITLE
Windows: Bad iperf3 results

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#487]
Driver: `9.9.2_3`
iPerf version: `3.1.3`
Yggdrasil version: `0.3.6-0026`
Command line: `iperf3 -6 -c 201:6779:c497:82f:68fd:188d:4338:1234`
OS: Windows 7 SP1 x64

Results are not just bad, they are totally wrong:
```
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec   256 KBytes   210 Kbits/sec                  sender
[  4]   0.00-10.00  sec  64.2 KBytes  52.6 Kbits/sec                  receiver
```

My node is connected directly to `201:6779:c497:82f:68fd:188d:4338:1234` peer with ping of 45ms.
My Internet connection have 100 Mbit/s bandwidth.

I think this problem may be related to #472 (#456).

**Comment by Vort** [comment]
One of the reasons for such bad result can be packet reordering.
It happens both during the sends and receives.
Most likely because of race conditions.

Test sequence: sending of 16 UDP packets with 1200 bytes size.
Tested version: `0.3.6-0043` (70a118ae98164e93ad122d187a18f1a0d0403b90)

![ygg_reorder](https://user-images.githubusercontent.com/1242858/62877444-bd62eb80-bd2f-11e9-8ac4-6bbf9fa308c8.png)

**Comment by neilalexander** [comment]
This is version `0.3.6-0043` on both ends of the test?

**Comment by Vort** [comment]
> This is version `0.3.6-0043` on both ends of the test?

Yes, it was modified with this patch:
```patch
diff --git a/src/yggdrasil/session.go b/src/yggdrasil/session.go
index da66ad5..6ec91b7 100644
--- a/src/yggdrasil/session.go
+++ b/src/yggdrasil/session.go
@@ -7,6 +7,7 @@ package yggdrasil
 import (
 	"bytes"
 	"errors"
+	"fmt"
 	"sync"
 	"time"
 
@@ -488,6 +489,9 @@ func (sinfo *sessionInfo) recvWorker() {
 					sinfo.updateNonce(&p.Nonce)
 					sinfo.time = time.Now()
 					sinfo.bytesRecvd += uint64(len(bs))
+					if bs[5] == 0xB8 && bs[0]&0xf0 == 0x60 {
+						fmt.Printf("My packet recv: #%d\n", bs[0x30]);
+					}
 				}
 				sinfo.doFunc(sessionFunc)
 				if err != nil {
@@ -593,6 +597,9 @@ func (sinfo *sessionInfo) sendWorker() {
 				util.PutBytes(p.Payload)
 				// Send the packet
 				sinfo.core.router.out(packet)
+				if msg.Message[5] == 0xB8 && msg.Message[0]&0xf0 == 0x60 {
+					fmt.Printf("My packet send: #%d\n", msg.Message[0x30]);
+				}
 			}
 			ch <- callback
 		} 
```
Black window is inside VM, receive side.
White window is on the host, send side.

**Comment by Vort** [comment]
One more test trying to catch send reordering:

![ygg_send_reorder](https://user-images.githubusercontent.com/1242858/62917451-fc7f5400-bda4-11e9-870d-c284ff0477fb.png)

```patch
diff --git a/src/tuntap/iface.go b/src/tuntap/iface.go
index 670f782..296d8d3 100644
--- a/src/tuntap/iface.go
+++ b/src/tuntap/iface.go
@@ -3,6 +3,7 @@ package tuntap
 import (
 	"bytes"
 	"errors"
+	"fmt"
 	"net"
 	"time"
 
@@ -164,6 +165,9 @@ func (tun *TunAdapter) readerPacketHandler(ch chan []byte) {
 			if n-tun_IPv6_HEADER_LENGTH != 256*int(bs[4])+int(bs[5]) {
 				continue
 			}
+			if bs[5] == 0xB8 {
+				fmt.Printf("My packet send (readerPacketHandler): #%d\n", bs[0x30]);
+			}
 			// IPv6 address
 			addrlen = 16
 			copy(srcAddr[:addrlen], bs[8:])
diff --git a/src/yggdrasil/session.go b/src/yggdrasil/session.go
index da66ad5..e4732cf 100644
--- a/src/yggdrasil/session.go
+++ b/src/yggdrasil/session.go
@@ -7,6 +7,7 @@ package yggdrasil
 import (
 	"bytes"
 	"errors"
+	"fmt"
 	"sync"
 	"time"
 
@@ -488,6 +489,9 @@ func (sinfo *sessionInfo) recvWorker() {
 					sinfo.updateNonce(&p.Nonce)
 					sinfo.time = time.Now()
 					sinfo.bytesRecvd += uint64(len(bs))
+					if bs[5] == 0xB8 && bs[0]&0xf0 == 0x60 {
+						fmt.Printf("My packet recv: #%d\n", bs[0x30]);
+					}
 				}
 				sinfo.doFunc(sessionFunc)
 				if err != nil {
@@ -593,6 +597,9 @@ func (sinfo *sessionInfo) sendWorker() {
 				util.PutBytes(p.Payload)
 				// Send the packet
 				sinfo.core.router.out(packet)
+				if msg.Message[5] == 0xB8 && msg.Message[0]&0xf0 == 0x60 {
+					fmt.Printf("My packet send (sendWorker): #%d\n", msg.Message[0x30]);
+				}
 			}
 			ch <- callback
 		} 
```

**Comment by Vort** [comment]
The same reordering happens when my host peer have no outgoing connections.
So network consists only of two nodes.

![ygg_reorder_single](https://user-images.githubusercontent.com/1242858/62932090-25fda700-bdc8-11e9-92cc-4545a6023984.png)

**Comment by Vort** [comment]
Retested with `0.3.7-0003`.
Here is how problem looks like in Wireshark:
![ygg_iperf](https://user-images.githubusercontent.com/1242858/63243392-15837b80-c263-11e9-8780-a876351aee27.png)

**Comment by Arceliar** [comment]
> Retested with `0.3.7-0003`.
> Here is how problem looks like in Wireshark:
> ![ygg_iperf](https://user-images.githubusercontent.com/1242858/63243392-15837b80-c263-11e9-8780-a876351aee27.png)

I see a little reordering due to how packets were buffered while we wait for a connection to open, which would only affect the first few packets in a session, and should be fixed in #517, but that can't be related to reordered packets later in the session.

I do see the occasional reordered packet in wireshark when I run on linux, but nothing near the level shown here. I'm still trying to figure out how that's possible (since, after the session is opened, if there's only 1 path between two nodes, then packets should arrive in-order or not at all).

**Comment by Arceliar** [comment]
So it looks like water (the tun/tap library we use) makes use of [Overlapped I/O](https://en.wikipedia.org/wiki/Overlapped_I/O) on Windows, which writes to the tap asynchronously.

I'm not sure if the later code waits for the write to finish, or just accepts that it will happen eventually (I'm not that familiar with Windows syscalls). If the write hasn't finished yet, and additional writes are done concurrently, then I wonder if perhaps they can be reordered by the OS.

**Comment by Vort** [comment]
@Arceliar packet reordering is gone with this patch. Both outgoing and incoming (I was not expecting that).
But instead reordering become replaced with massive packet drops (which means iperf3 still can't work).
Also I see (as before, forgot to said it) huge lags. Last bunch of packets can be delayed for 10-15 seconds!
It may be somehow related to my low memory conditions because of VM running, but 10 seconds is too much even for VM.

**Comment by Vort** [comment]
Fresh iperf3 results:
```
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec   256 KBytes  2.08 Mbits/sec
[  4]   1.01-2.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   2.01-3.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   3.00-4.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   4.01-5.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   5.01-6.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   6.01-7.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   7.01-8.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   8.00-9.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   9.01-10.02  sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.02  sec   256 KBytes   209 Kbits/sec                  sender
[  4]   0.00-10.02  sec  2.38 KBytes  1.95 Kbits/sec                  receiver
```
![iperf_new](https://user-images.githubusercontent.com/1242858/63489412-b4ee7b80-c4ba-11e9-8405-5f395ff6b539.png)

**Comment by Vort** [comment]
What I see here is 65549 bytes packet!
Tried to test this size with pings - and fail!
That is most likely another bug in TAP driver.
`tap-windows-9.21.2` was failing with something around 1.5k.
And `tap-windows-9.9.2_3.exe` starts to fail exactly at ping size of 65474 (which means packet size of 65536)

**Comment by Vort** [comment]
@Arceliar most likely, the "fix" for this problem consists of lowering of default MTU for Windows.
Here is what I have with `IfMTU: 65521`:
VM <--> host
```
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  1.12 MBytes  9.43 Mbits/sec
[  4]   1.00-2.01   sec   640 KBytes  5.21 Mbits/sec
[  4]   2.01-3.01   sec  1.00 MBytes  8.39 Mbits/sec
[  4]   3.01-4.00   sec  1.25 MBytes  10.5 Mbits/sec
[  4]   4.00-5.01   sec   512 KBytes  4.18 Mbits/sec
[  4]   5.01-6.01   sec   640 KBytes  5.25 Mbits/sec
[  4]   6.01-7.00   sec   640 KBytes  5.27 Mbits/sec
[  4]   7.00-8.00   sec   640 KBytes  5.24 Mbits/sec
[  4]   8.00-9.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   9.00-10.00  sec   640 KBytes  5.25 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  7.25 MBytes  6.08 Mbits/sec                  sender
[  4]   0.00-10.00  sec  7.06 MBytes  5.92 Mbits/sec                  receiver
```
Host <--> ygg.thingylabs.io:
```
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   384 KBytes  3.15 Mbits/sec
[  4]   1.00-2.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   2.00-3.00   sec   768 KBytes  6.29 Mbits/sec
[  4]   3.00-4.00   sec   640 KBytes  5.24 Mbits/sec
[  4]   4.00-5.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   5.00-6.00   sec   640 KBytes  5.24 Mbits/sec
[  4]   6.00-7.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   7.00-8.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   8.00-9.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   9.00-10.00  sec   256 KBytes  2.10 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  3.88 MBytes  3.25 Mbits/sec                  sender
[  4]   0.00-10.00  sec  3.75 MBytes  3.15 Mbits/sec                  receiver
```

There are lot of space for improvements.
But at least it works now.

**Comment by Vort** [comment]
I have made two additional tests with Lubuntu 17.10 (default IfMTU) and Windows 8.1 (IfMTU: 65521, driver `9.9.2_3`) inside VirtualBox (host: Win7SP1x64) with version `0.3.8-0002`.
With Lubuntu 17.10: no reordering and losses at all.
With Windows 8.1: same results as with Windows 7 (lots of reordered packets).
So if you don't have Windows 7, later Windows versions most likely can be used for reproduction too.

**Comment by Vort** [comment]
Most of the problems with bandwidth on Windows platform are fixed now. I will open additional reports if find how situation can be improved even more. Thanks for the fixing.
